language: cpp

compiler:
  - gcc
  #- clang

os:
  - linux
  #- osx

script:
  - export TOP=$(pwd)
  - git clone https://github.com/MathiasMagnus/OpenCL-Headers.git --branch pkgconfig --single-branch
  - cd ${TOP}/OpenCL-Headers
  - ln -s CL OpenCL # For OSX builds
  - mkdir build
  - mkdir install
  - cd build
  - cmake -D CMAKE_INSTALL_PREFIX=../install
          ..
  - cmake --build .
          --target install
  - cd ${TOP}
  - mkdir build
  - mkdir install
  - cd build
  - cmake -D BUILD_TESTING=OFF # icd_loader_test is defunct
          -D CMAKE_INSTALL_PREFIX=../install
          -D CMAKE_PREFIX_PATH=${TOP}/OpenCL-Headers/install ..
  - cmake --build .
          --target install
  - ctest
