linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc49-armv7hf
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc5-armv7hf
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc6-armv7hf
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc7-armv7hf
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc8-armv7hf
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc5-armv8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc6-armv8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc7-armv8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc8-armv8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1
    - <<: *osx
      osx_image: xcode9
      env: CONAN_APPLE_CLANG_VERSIONS=9.0
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1
    - <<: *osx
      osx_image: xcode10.1
      env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
