stages:
  - build   # Test if headers build and install (CMake)
  - test    # Test if unit tests pass (CTest)
  - consume # Test if downstream can depend on installs (CMake)

variables:
  DEPS_DIR:      "$CI_PROJECT_DIR/dependencies"
  BUILD_DIR:     "$CI_PROJECT_DIR/build"
  INSTALL_DIR:   "$CI_PROJECT_DIR/install"
  CMAKE_MINIMUM: "3.1.3"
  CMAKE_LATEST:  "3.21.2"

########################
##                    ##
## Setup environments ##
##                    ##
########################

.toolchain-matrix-minimum:
  image: streamhpc/opencl-sdk-base:ubuntu-18.04-20210910
  parallel:
    matrix:
  # NOTE: Old CMake versions will likely not use cutting-edge compilers
      - COMPILER: [gcc-7, gcc-8, clang-8, clang-9, clang-10]
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_MINIMUM/bin:$PATH

.toolchain-matrix-latest:
  image: streamhpc/opencl-sdk-base:ubuntu-18.04-20210910
  parallel:
    matrix:
  # NOTE: Cutting edge CMake versions will likely not use old compilers
      - COMPILER: [gcc-9, gcc-10, clang-11, clang-12, clang-13]
  before_script:
    - export PATH=/opt/Kitware/CMake/$CMAKE_LATEST/bin:$PATH


#################
##             ##
## Build stage ##
##             ##
#################

build:cmake-minimum:
  extends: .toolchain-matrix-minimum
  stage: build
  # NOTE 1: CMake creates build and install folders as needed.
  # NOTE 2: Lack of space in -H<folder> -B<folder> is important!
  #         https://stackoverflow.com/a/20611964/1476661
  script:
    # Clone, configure, build, install OpenCL-Headers
    # NOTE: OpenCL-Headers URL set in repo settings
    - git clone
      --depth 1
      --branch develop_stream
      https://gitlab-ci-token:${CI_JOB_TOKEN}@${OPENCL_HEADERS_GIT_URL}
      $DEPS_DIR/OpenCL-Headers
    - cmake
      -G Ninja
      -D CMAKE_C_COMPILER=$COMPILER
      -D CMAKE_BUILD_TYPE=Release
      -D BUILD_TESTING=OFF
      -D CMAKE_INSTALL_PREFIX=$DEPS_DIR/OpenCL-Headers/install
      -B$DEPS_DIR/OpenCL-Headers/build
      -H$DEPS_DIR/OpenCL-Headers
    - cmake
      --build $DEPS_DIR/OpenCL-Headers/build
      --target install
    # Configure, build, install OpenCL-ICD-Loader
    - cmake
      -G Ninja
      -D CMAKE_CXX_COMPILER=$COMPILER
      -D CMAKE_BUILD_TYPE=Release
      -D BUILD_TESTING=ON
      -D CMAKE_PREFIX_PATH=$DEPS_DIR/OpenCL-Headers/install
      -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR
      -B$BUILD_DIR
      -H$CI_PROJECT_DIR
    - cmake
      --build $BUILD_DIR
      --target install
  artifacts:
    paths:
      - build/
      - install/
    exclude:
      - build/**/CMakeFiles/
    expire_in: 2 weeks

build:cmake-latest:
  extends: .toolchain-matrix-latest
  stage: build
  script:
    # Clone, configure, build, install OpenCL-Headers
    # NOTE: OpenCL-Headers URL set in repo settings
    - git clone
      --depth 1
      --branch develop_stream
      https://gitlab-ci-token:${CI_JOB_TOKEN}@${OPENCL_HEADERS_GIT_URL}
      $DEPS_DIR/OpenCL-Headers
    - cmake
      -G "Ninja Multi-Config"
      -D CMAKE_C_COMPILER=$COMPILER
      -D BUILD_TESTING=OFF
      -D CMAKE_INSTALL_PREFIX=$DEPS_DIR/OpenCL-Headers/install
      -B$DEPS_DIR/OpenCL-Headers/build
      -H$DEPS_DIR/OpenCL-Headers
    - cmake
      --build $DEPS_DIR/OpenCL-Headers/build
      --config Debug
      --target install
    - cmake
      --build $DEPS_DIR/OpenCL-Headers/build
      --config Release
      --target install
    # Configure, build, install OpenCL-ICD-Loader
    - cmake
      -G "Ninja Multi-Config"
      -D CMAKE_C_COMPILER=$COMPILER
      -D BUILD_TESTING=ON
      -D CMAKE_PREFIX_PATH=$DEPS_DIR/OpenCL-Headers/install
      -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR
      -B $BUILD_DIR
      -S $CI_PROJECT_DIR
    - cmake
      --build $BUILD_DIR
      --config Debug
      --target install
    - cmake
      --build $BUILD_DIR
      --config Release
      --target install
  artifacts:
    paths:
      - build/
      - install/
    exclude:
      - build/**/CMakeFiles/
    expire_in: 2 weeks


################
##            ##
## Test stage ##
##            ##
################

test:cmake-minimum:
  extends: .toolchain-matrix-minimum
  stage: test
  needs:
    - build:cmake-minimum
  # NOTE: CTest has to be invoked from the build folder.
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure

test:cmake-latest:
  extends: .toolchain-matrix-minimum
  stage: test
  needs:
    - build:cmake-latest
  # NOTE: CTest has to be invoked from the build folder.
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure -C Debug
    - ctest --output-on-failure -C Release 
